# Generated by Django 3.1.12 on 2021-08-05 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(db_index=True, default=None, null=True),
                ),
                (
                    "subuser_id",
                    models.IntegerField(db_index=True, default=None, null=True),
                ),
                ("nickname", models.CharField(default="", max_length=150, null=True)),
                (
                    "action_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="action time",
                    ),
                ),
                (
                    "action_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Debug"),
                            (1, "Info"),
                            (2, "Warning"),
                            (3, "KeyFrame"),
                            (10, "Error"),
                        ],
                        default=1,
                        verbose_name="action level",
                    ),
                ),
                (
                    "action_type",
                    models.PositiveSmallIntegerField(verbose_name="action type"),
                ),
                ("action_ip", models.GenericIPAddressField()),
                (
                    "action_name",
                    models.CharField(max_length=100, verbose_name="action name"),
                ),
                ("object_type", models.CharField(max_length=100)),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="object id"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=200, verbose_name="object repr"),
                ),
                (
                    "change_message",
                    models.TextField(blank=True, verbose_name="change message"),
                ),
            ],
            options={
                "ordering": ["-action_time"],
            },
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="epub_logs_l_object__347b2a_idx",
            ),
        ),
    ]
