# Generated by Django 3.2.22 on 2024-12-09 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epub_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action_name',
            field=models.TextField(blank=True, verbose_name='action name'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='action time'),
        ),
    ]
