# Generated by Django 3.1 on 2021-04-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("epub_labels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("show_in_list", models.BooleanField(default=False)),
                ("can_query", models.BooleanField(default=False)),
                (
                    "linked_app",
                    models.CharField(
                        choices=[("cbt", "CBT"), ("quiz", "QUIZ"), ("doc", "DOC")],
                        default="cbt",
                        max_length=15,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="epub_labels.label",
                    ),
                ),
            ],
            options={
                "unique_together": {("label", "linked_app")},
            },
        ),
    ]
