# Generated by Django 3.1 on 2021-04-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epub_labels", "0003_auto_20210408_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="applabel",
            name="nickname",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="applabel",
            name="subuser_id",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="applabel",
            name="user_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
