# Generated by Django 3.1.12 on 2021-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epub_labels", "0004_auto_20210413_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applabel",
            name="linked_app",
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
