# Generated by Django 3.1.14 on 2023-01-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epub_labels', '0005_auto_20210717_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='input_type',
            field=models.IntegerField(choices=[(0, 'single'), (1, 'multiple'), (2, 'input'), (3, 'bool')]),
        ),
        migrations.AlterField(
            model_name='label',
            name='value_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'number'), (3, 'bool')]),
        ),
    ]
