# Generated by Django 3.1.14 on 2023-03-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epub_labels", "0006_auto_20230112_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applabel",
            name="linked_app",
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
