# Generated by Django 3.1.12 on 2021-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="label",
            field=models.JSONField(null=True),
        ),
    ]
