# Generated by Django 3.1 on 2021-07-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("epub_folders", "0001_initial"),
        ("books", "0003_book_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="epub_folders.folder",
            ),
        ),
    ]
