# Generated by Django 3.1.12 on 2022-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='subuser_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
