# Generated by Django 3.2.22 on 2025-02-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dept_id',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subuser_id',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
    ]
